import React, {Component} from 'react';
import {Rectangle, Container, Row, Col, Nav, Navbar, NavItem, Button, Form, FormGroup, Input, Group, GroupFixed, Image, SketchDocument, Text, TextPart, ExternalAsset} from '@sketch2react/react-components';
import * as StyleVariables from './StyleVariables/StartStyleVariables';



 import './css/start_fonts.css'

class Start extends Component { 
  /* constructor(props){
    super(props);
  } */
  
  /* lifecycle handlers goes here */
  
  render(){
    return(<SketchDocument>
  <Container>
    <Row>
      <Col xs="12">
        <Text id="txt_3789" htmlType="p" className="m16">
          <TextPart id="txt_part_0" sketchStyle={StyleVariables.txt_3789_txt_part_0_SketchStyle}>Why is Eburus free?</TextPart>
          <TextPart id="txt_part_1" sketchStyle={StyleVariables.txt_3789_txt_part_1_SketchStyle}>Eburus is free forever because our goal is to help as many people as possible to successfully complete their advance care planning. We make money by promoting our affiliate partners who offer services and products that our users will appreciate.</TextPart>
          <TextPart id="txt_part_2" sketchStyle={StyleVariables.txt_3789_txt_part_2_SketchStyle}>How does Eburus work?</TextPart>
          <TextPart id="txt_part_3" sketchStyle={StyleVariables.txt_3789_txt_part_3_SketchStyle}>Eburus provides a list of advance care planning questions. We ask that you fill out the questions as openly and honestly as you can. After filling out the questions, we assess what your needs are and send you a list of curated services for you can use, if you wish. You are also sent a copy of your answers for safe keeping. We encourage you to share your answers with family members and people providing you care such as doctors and nurses. </TextPart>
          <TextPart id="txt_part_4" sketchStyle={StyleVariables.txt_3789_txt_part_4_SketchStyle}>What is an Advance Care or End-of-Life plan?</TextPart>
          <TextPart id="txt_part_5" sketchStyle={StyleVariables.txt_3789_txt_part_5_SketchStyle}>Advance care or end of life planning involves making a plan for future health and personal care should a person lose their decision-making capacity. Advance care planning captures peoples' values and wishes. It enables them to continue to influence treatment decisions, even when they can no longer actively participate.</TextPart>
          <TextPart id="txt_part_6" sketchStyle={StyleVariables.txt_3789_txt_part_6_SketchStyle}>What type of questions do you ask?</TextPart>
          <TextPart id="txt_part_7" sketchStyle={StyleVariables.txt_3789_txt_part_7_SketchStyle}>Eburus asks you questions that are normally not covered in your will. This includes things you may not have thought about like:- Detailed wishes for end-of-life medical care- Ideas for a more personalized and comforting funeral- Ideas for unique ways to memorialize someone- A digital asset plan (e.g., social media, online accounts, etc)- Continued care plan for pet(s) - A bucket list for things you’d still like to accomplishThese questions help you and your family understand and carry out your wishes in the unfortunate event of your passing. </TextPart>
          <TextPart id="txt_part_8" sketchStyle={StyleVariables.txt_3789_txt_part_8_SketchStyle}>Are the answers to these questions legally binding?</TextPart>
          <TextPart id="txt_part_9" sketchStyle={StyleVariables.txt_3789_txt_part_9_SketchStyle}>These questions are for you and your family to think about. We encourage you to take your answers to your GP or primary care physician and discuss it with them. They can input this information into your electronic medical or health records, if you wish. Not all end-of-life decisions need to be in legal documents to come true. For example, if you want to play Beyonce or Fleetwood Mac at your funeral, your loved ones just have to know about it for them to carry this out. The most important thing for these types of decisions is to make sure they are known so that they can be honored. As you answer questions on Eburus, we generate documents that record your wishes for things like funeral, memorial, legacy, and pet care decisions. While these planning documents don't need to be legally binding, they provide invaluable guidance to your loved ones to carry out your wishes and honor your life in the way that is most true to who you are.</TextPart>
          <TextPart id="txt_part_10" sketchStyle={StyleVariables.txt_3789_txt_part_10_SketchStyle}>How do you curate the services you recommend to me?</TextPart>
          <TextPart id="txt_part_11" sketchStyle={StyleVariables.txt_3789_txt_part_11_SketchStyle}>We look at the answers you provided and match your needs with services we have. We never share your data with any third party providers. We send you a list of providers we think you could use, and if you choose to use them, you can reach out via the links and discount codes we offer. We only work with leading providers in the advance care space.</TextPart>
          <TextPart id="txt_part_12" sketchStyle={StyleVariables.txt_3789_txt_part_12_SketchStyle}>Do you share my answers with your providers?</TextPart>
          <TextPart id="txt_part_13" sketchStyle={StyleVariables.txt_3789_txt_part_13_SketchStyle}>We have never shared and will never share your data with any third party providers. Your information belongs to you and our role is simply to take care of it. If you wish to delete your information, simply email us at contact@eburus.com and it will be removed within 24 hours. </TextPart>
          <TextPart id="txt_part_14" sketchStyle={StyleVariables.txt_3789_txt_part_14_SketchStyle}>Is my profile secure and private? Can I trust Eburus with my data?</TextPart>
          <TextPart id="txt_part_15" sketchStyle={StyleVariables.txt_3789_txt_part_15_SketchStyle}>Yes and yes! The Eburus team takes your security very seriously. We are HIPAA compliant, employ bank-level security, and all of your data is protected in transit and at rest with 256-bit AES encryption and 2048-bit certificates. Eburus is GDPR compliant for our European users, which simply means we abide by strict European Union rules for handling, protecting, and allowing users to manage their own data. Your profile and answers are completely private to you and only you by default. This means that we only share your data with people that you choose to share your profile with. We recommend that you share your profile with the important people in your life; that is how you get value out of your Eburus profile.  **Can we prove this?**We do not sell or share personally identifiable information (PII) with any 3rd party. We are committed to protecting your privacy and security, as outlined in our Privacy Policy and Terms of Use.If you wish to delete your information, simply email us at contact@eburus.com and it will be removed within 24 hours.</TextPart>
          <TextPart id="txt_part_16" sketchStyle={StyleVariables.txt_3789_txt_part_16_SketchStyle}>How long does it take to complete the questionnaire?</TextPart>
          <TextPart id="txt_part_17" sketchStyle={StyleVariables.txt_3789_txt_part_17_SketchStyle}>We estimate it takes about 20 minutes. This time can vary based on a number of factors.</TextPart>
          <TextPart id="txt_part_18" sketchStyle={StyleVariables.txt_3789_txt_part_18_SketchStyle}>Do I have to fill out the form at once?</TextPart>
          <TextPart id="txt_part_19" sketchStyle={StyleVariables.txt_3789_txt_part_19_SketchStyle}>Not at all! You can fill out as much as you like and as long as you input your email, we will follow up with where you left off.</TextPart>
          <TextPart id="txt_part_20" sketchStyle={StyleVariables.txt_3789_txt_part_20_SketchStyle}>Why the name Eburus?</TextPart>
          <TextPart id="txt_part_21" sketchStyle={StyleVariables.txt_3789_txt_part_21_SketchStyle}>Eburus is derived from the word 'ebur' - which is associated with ivory and elephants. While Eburus could be a play on the durable and valuable nature of ivory, we find the relation to elephants much more appealing. Elephants have long been considered one of the most empathetic animals. They have strong social groups, often console each other in times of need, and are one of the few animals with a burial ritual. When we were thinking of a name for a business that helps people plan the next stage of their lives, we thought of elephants and came up with the name 'ebur - us'. This is because we are also like the elephants in our care and respect for one another.</TextPart>
          <TextPart id="txt_part_22" sketchStyle={StyleVariables.txt_3789_txt_part_22_SketchStyle}>Why did you create Eburus?</TextPart>
          <TextPart id="txt_part_23" sketchStyle={StyleVariables.txt_3789_txt_part_23_SketchStyle}>The reality of life is that everyone will die someday. Each and every one of us should have a say in how we live our lives, from beginning to end. We don’t think about these things until it’s too late, and we want to change that. Not making these decisions is also costly to our healthcare systems and at Eburus, we thought we could change that.Eburus is particularly helpful for anyone who wants to:- Make sure their wishes are known and followed- Get guidance on what planning they should do- Know if the planning they have already done is sufficient- Unburden their loved ones from having to make these decisions for them someday- Help their aging parents plan- Protect their children or spouse should anything happen to them- Protect their adult dependents should anything happen to them- Have more peace of mind and perspective - Ultimately preparation for end of life benefits everyone, their families and the health systems at large. </TextPart>
          <TextPart id="txt_part_24" sketchStyle={StyleVariables.txt_3789_txt_part_24_SketchStyle}>What is the difference between Eburus, a Will and Power of Attorney? </TextPart>
          <TextPart id="txt_part_25" sketchStyle={StyleVariables.txt_3789_txt_part_25_SketchStyle}>A will is a legal document that indicates how you want your estate (money and property) to be distributed after your passing.  A power of attorney is a document you can use to appoint someone to make decisions on your behalf. The person you designate is called an "attorney-in-fact." The appointment can be effective immediately or can become effective only if you are unable to make decisions on your own. The person who has your power of attorney is your substitute decision maker.Eburus is not an online Will or Power of Attorney service. Our goal is to help you think about your advance care. Advance care planning involves making a plan for future health and personal care should your lose your decision-making capacity. Advance care planning captures peoples' values and wishes. It enables you to continue to influence treatment decisions, even when you can no longer actively participate.</TextPart>
          <TextPart id="txt_part_26" sketchStyle={StyleVariables.txt_3789_txt_part_26_SketchStyle}>Can I download my answers?</TextPart>
          <TextPart id="txt_part_27" sketchStyle={StyleVariables.txt_3789_txt_part_27_SketchStyle}>Ofcourse! We will send you a PDF copy of your answers through the email you provide. </TextPart>
          <TextPart id="txt_part_28" sketchStyle={StyleVariables.txt_3789_txt_part_28_SketchStyle}>I've already done my planning on paper. Should I sign up for this?</TextPart>
          <TextPart id="txt_part_29" sketchStyle={StyleVariables.txt_3789_txt_part_29_SketchStyle}>Amazing, congratulations on already thinking about this! A worry a lot of offline planners express is that their paper documents might not be found by family when they are needed. Think of Eburus as an online booklet for all of your current end-of-life wishes and documents. We'll also help you explore other preferences that most traditional planning tools do not cover. </TextPart>
          <TextPart id="txt_part_30" sketchStyle={StyleVariables.txt_3789_txt_part_30_SketchStyle}>I already have a will. What does Eburus offer that a will does not?</TextPart>
          <TextPart id="txt_part_31" sketchStyle={StyleVariables.txt_3789_txt_part_31_SketchStyle}>A will is a great start! However, there are many end-of-life preferences that a standard will does not always address. Eburus helps you think through the personal, human preferences that a will may overlook: - Detailed wishes for end-of-life medical care- Ideas for a more personalized and comforting funeral- Ideas for unique ways to memorialize someone- A digital asset plan (e.g., social media, online accounts, etc)- Continued care plan for pet(s) Those are just a few examples. Eburus helps uncover your values across all areas of life so you can be clearer on your preferences, and so your loved ones can be clear on them, too.</TextPart>
          <TextPart id="txt_part_32" sketchStyle={StyleVariables.txt_3789_txt_part_32_SketchStyle}>I don’t care what happens after I die. I’ll be dead. Should I sign up for this?</TextPart>
          <TextPart id="txt_part_33" sketchStyle={StyleVariables.txt_3789_txt_part_33_SketchStyle}>Not caring what happens after you die is a totally valid preference! You can use Eburus to make sure your loved ones know that you don’t care so they are free to make their own decisions. You can also use Eburus to explore other aspects of end of life that you might not have been aware of and may have an opinion about.</TextPart>
          <TextPart id="txt_part_34" sketchStyle={StyleVariables.txt_3789_txt_part_34_SketchStyle}>How did you come up with the content and questions presented in the Eburus platform?</TextPart>
          <TextPart id="txt_part_35" sketchStyle={StyleVariables.txt_3789_txt_part_35_SketchStyle}>We've worked closely with palliative care physicians, social workers, wealth managers, estate attorneys, and funeral planners. We have also seen the rise of many of these planning services around the world and made sure the experience we provide is the best it could be. </TextPart>
          <TextPart id="txt_part_36" sketchStyle={StyleVariables.txt_3789_txt_part_36_SketchStyle}>What happens to my plan if Eburus isn't around in 50 years?</TextPart>
          <TextPart id="txt_part_37" sketchStyle={StyleVariables.txt_3789_txt_part_37_SketchStyle}>Rest assured, you will not lose any planning you do with Eburus! We greatly value the trust our users place in us to keep their plans safe and secure for the long term. That said, we understand the concern some people may have about saving their end-of-life plans online with a company. We are committed to protecting the information in your profile, no matter what the future holds. You own all of the personal information in your Eburus profile, and you can download or print your planning at any time. In the event Eburus would need to cease operations, we would ensure our users receive access to a copy of their plan for printing or digital safekeeping elsewhere.Don't see your question here?  Contact us! Link to contact@eburus.com</TextPart>
        </Text>
      </Col>
    </Row>
    <Button color="primary" id="null">
      <Text id="txt_4313" htmlType="p" sketchStyle={StyleVariables.txt_4313_SketchStyle}>ADVANCED CARE PLAN</Text>
    </Button>
  </Container>
</SketchDocument>)
  }
}

export default Start;